server:
  port: 8080

spring:
  application:
    name: service-a

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"

app:
  service-b:
    url: http://localhost:8081/hello
